### ISSUE TITLE
Option to color books by series instead of reading order

### ISSUE THREAD

**Issue by jofwu** [PaleoCrafter/reading-order#11]
I think it would be beneficial to have an option to color books by their series instead of the reading order phase colors.

I have added series categories and assigned books to them. It would be nice if there were a toggle to have the books colored according to these instead of the blue/green phase categories. With things set up the way they are now, I'm _guessing_ this isn't possible. It's just styling the text according to whatever was slapped on last. So I'm guessing the json file would need to be reworked for this, to something more like what you've done with "sorting".

**Comment by PaleoCrafter** [comment]
Addressed through addition of layers whose styles can be toggled.
