### ISSUE TITLE
Additional indication of book series and/or world

### ISSUE THREAD

**Issue by jofwu** [PaleoCrafter/reading-order#12]
Aside from the coloring books by series (Issue #11) I wondered if it would be good to graphically indicate series or worlds by some other means.

I sent this image last week:
![series](https://user-images.githubusercontent.com/8247331/68727224-cdd66c80-0591-11ea-8fcd-663803bde473.png)

This definitely has issues with clutter. I think I may have proposed just showing one at a time. A way to choose neither, by world, or by series. I think you proposed having it fade in depending on zoom level. All potential ways to do it.

I've also wondered about a more minimalist way of doing it along the same line of thought. Instead of putting those arcs on the outside of the circle, you could put them on the inside, between the books and the ends of the arrows. They could all be a uniform color or be colored the same way the series categories are? You wouldn't put any text directly on the graphic. The arc would just be used to show that those books are tied together, either as a series or on the same world. Maybe if you hover the mouse on the arc it makes a label show up, or you get a tooltip.

It would only make sense to do this on the series view. I'm not sure how you'd specify where the arcs start and end programatically. 

Just some thoughts...

**Comment by PaleoCrafter** [comment]
Implemented and deployed with the latest commit. All non-book levels of the entries can now have a label associated with them that'll get displayed as an arc covering all related books.

Example:
![Label example](https://i.imgur.com/WTZzr3l.png)
