### ISSUE TITLE
Ability to hide side bar and overlay

### ISSUE THREAD

**Issue by Quantumplation** [PaleoCrafter/reading-order#17]
Hi! Love the this tool, and mad that I didn't make it myself. ;)

I'd love the ability to hide the sidebar and the overlay in the top-left corner, so I can take a nice screenshot.  Alternatively, the ability to just download a high resolution image for a desktop background would be great!

**Comment by jofwu** [comment]
I think this is working in mobile. Maybe a benefit to having it on desktop?

**Comment by Quantumplation** [comment]
Oh hey! I saw a comment by you on reddit the other day and was like "... where the hell do I know that name from?" lol :)
