### ISSUE TITLE
Some connections missing in Rhythm of War? 

### ISSUE THREAD

**Issue by Fairasname** [PaleoCrafter/reading-order#30]
Hi,

First, awesome diagram this one is! 

Also, I was checking the connections between Rhythm of War and other works and I think there are a couple missing:

-Elantris: Mraize and Wit's Seons (inside the communication device Mraize gives to Shallan/Wit also uses).

-Sixth of the Dusk: Lift's new Aviar (and Mraize one, if not stated yet).

-White Sand: The white sand Raboniel gives to Navani and Vyre also uses. 

Thanks!

**Comment by cmpickle** [comment]
Fixed by cead43f8cf00a701c4769373e6d6f52d57441ab3
