### ISSUE TITLE
Hope of Elantris reading order

### ISSUE THREAD

**Issue by Phoboskomboa** [PaleoCrafter/reading-order#33]
Hope of Elantris is set before Elantris on the wheel and it definitely should NOT be read before as it is set during the climax and contains major spoilers for Elantris.

**Comment by Cargonat** [comment]
I agree. There is already a commit [here](https://github.com/PaleoCrafter/reading-order/commit/85acf17ab48a311a1e6400b020ef536fb860f56d) that should do this however. I believe it might not yet be deployed to GitHub pages.

**Comment by jofwu** [comment]
Oh, my bad. I merged the commit, but never deployed it yeah. :D
